name: colormoves
services:
  colormoves:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: taccwma/colormovestacc:latest
    volumes:
      - .:/colormoves
      - /colormoves/src/node_modules   # ← anonymous volume protects node_modules
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
    command: ['--report-compact']
    container_name: colormoves
    hostname: colormoves
    restart: always
