version: '3.8'
services:
  colormoves:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: taccwma/colormovestacc:latest
    volumes:
      - .:/colormoves
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
    command: ['--report-compact']
    container_name: colormoves
    hostname: colormoves
    restart: always
